### ISSUE TITLE
Notifications not displaying

### ISSUE THREAD

**Issue by danielgrimshaw** [Thunderbots-5604/Thunderbots-Website#2]
It appears that I have found a fault in the code. Also, I have worked out a way to decode the passwords, but so far I haven't been able to get the passwords that are not mine.

**Comment by zachw000** [comment]
I know it doesn't display I'm working with the code right now, seems to be a problem with the JSON file.

**Comment by zachw000** [comment]
I still don't know why though it just stopped working.

**Comment by zachw000** [comment]
Ok so it seems the reason is that the data is unescaped still, except for angle brackets, and that has caused an unexpected token error, so I will escape the input real quick so this won't happen, but otherwise the notification code was fine.

**Comment by zachw000** [comment]
Ok notifications does display now.
