### ISSUE TITLE
Hit hosting limit

### ISSUE THREAD

**Issue by zachw000** [Thunderbots-5604/Thunderbots-Website#4]
After commit e922af6bd9d0300e4d7aca8cac11d0bbbd175b37 we have hit the upload limit on the server we currently use to host the web site on, so until we find another (semi-trustworthy) host we are going to have to use the previous web site version found at http://www.thunderbots.tk/

**Comment by zachw000** [comment]
Switching hosts fixed PHP problem and fixed hosting limit problem.

**Comment by danielgrimshaw** [comment]
@zachw000 I don't think x10hosting has an upload limit. It is also fairly secure.

**Comment by zachw000** [comment]
@danielgrimshaw This was before I transferred to x10hosting, thunderbots.tk is still hosted on the other server, but for now, the new code is on http://www.thunderbots.x10host.com/. Yes, there is an upload limit on x10hosting of 100mb of total disk space.
